CREATE OR ALTER PROC FI_SP_VerificaClienteV2
	@ID BIGINT,
	@CPF VARCHAR(11)
AS
BEGIN
	SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND ID != @ID
END

--CREATE OR ALTER PROC FI_SP_VerificaCliente
--	@CPF VARCHAR(14)
--AS
--BEGIN
--	SELECT 1 FROM CLIENTES WHERE CPF = @CPF
--END